# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 802f06d3511174338a0e1d47576f505569f14946321e1d0c2b5869015a0484c1158fc20b9c4ee10ba9c52a552307804a044826ec28c7eb9fc392ab265b327e0c

test:
  secret_key_base: 21d2983e670126a2d25bb6ed6b985299e3c9e48b539018e467b21fb66a88a362d5e110f6116861ab194ccd3da3f59ce4273b0630ad1f54e471fd67d6c6fb4507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
